# Generated by Django 5.2.7 on 2025-10-15 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('modules', '0002_rename_author_module_author_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('last_module_learned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('modules_available', models.ManyToManyField(to='activities.activity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
