# Generated by Django 5.2.7 on 2025-10-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_progress_useroverview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroverview',
            old_name='last_module_learned',
            new_name='last_module_learned_id',
        ),
    ]
