# Generated by Django 5.2.7 on 2025-10-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_rename_last_module_learned_useroverview_last_module_learned_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroverview',
            old_name='modules_available',
            new_name='user_activities',
        ),
    ]
