# Generated by Django 5.2.7 on 2025-11-15 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_testhistory'),
        ('modules', '0004_rename_author_id_module_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testhistory',
            options={'ordering': ['-date_finished']},
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='correct_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_histories', to='modules.lesson'),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]