# Generated by Django 5.2.7 on 2025-11-15 00:42

from django.db import migrations


def migrate_testhistory_data(apps, schema_editor):
    # Get models
    TestHistory = apps.get_model('activities', 'TestHistory')
    Lesson = apps.get_model('modules', 'Lesson')
    
    # Update any existing TestHistory records
    # Since we don't have a way to map lesson_id to Lesson objects,
    # we'll just set them to None for now
    TestHistory.objects.filter(lesson_id__isnull=False).update(lesson=None)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_testhistory_lesson_alter_testhistory_student'),
    ]

    operations = [
        migrations.RunPython(migrate_testhistory_data, reverse_code=migrations.RunPython.noop),
    ]