# Generated by Django 5.2.7 on 2025-10-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='author',
            new_name='author_id',
        ),
    ]
