# Generated by Django 5.2.7 on 2025-10-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='author_id',
            new_name='author',
        ),
    ]
